[package]
name = "pillar-config"
description = "Environment, provider, wallet and LayerZero static configuration for the Pillar DVN client."
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile = "3"
